### ISSUE TITLE
Increase the automated test coverage to an acceptable value

### ISSUE THREAD

**Issue by cristim** [cristim/autospotting#7]
I'd like to see it achieve somewhere around 80%

Summary of files:
* [x] autoscaling (ref https://github.com/cristim/autospotting/issues/41)
* [x] connections (no ref)
* [x] instance (ref https://github.com/cristim/autospotting/issues/42)
* [x] launch_configuration (ref https://github.com/cristim/autospotting/issues/43)
* [ ] main (no ref)
* [ ] region (ref https://github.com/cristim/autospotting/issues/44)
* [x] spot_instance_request (ref https://github.com/cristim/autospotting/issues/45)
* [x] spot_price (no ref)

**Comment by xlr-8** [comment]
I guess we can close it now: https://coveralls.io/github/cristim/autospotting?branch=master

Except `region.go` & `main.go` the coverage of the other one has been reached, and overall coverage as well.

**Comment by cristim** [comment]
Thanks, I'll close this.

But I'd like to also increase the coverage on region.go and main.go at some point.

**Comment by xlr-8** [comment]
Agreed, which is why I created a new one, and update this description.
